//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Asistencia.Data_Access.Conection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        public int ID_Curso { get; set; }
        public string Curso { get; set; }
        public string Habilitado { get; set; }
    }
}
