//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Asistencia.Data_Access.Conection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Sistema_Asistencia_ProfesorEntities : DbContext
    {
        public Sistema_Asistencia_ProfesorEntities()
            : base("name=Sistema_Asistencia_ProfesorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<Cursos> Cursos { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
    
        public virtual ObjectResult<Reporte_Estudiante_Sin_Asistir_Result> Reporte_Estudiante_Sin_Asistir(string fecha, string curso)
        {
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            var cursoParameter = curso != null ?
                new ObjectParameter("curso", curso) :
                new ObjectParameter("curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reporte_Estudiante_Sin_Asistir_Result>("Reporte_Estudiante_Sin_Asistir", fechaParameter, cursoParameter);
        }
    }
}
